import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  
  const [name, setName] = useState("dog");
  
  const [buttonName, setButtonName] = useState("OFF")

  const [showPic, setShowPic] = useState(false); 

  function showCat()
  {
    if(!showPic)
    {
      setShowPic(true);
      setButtonName("ON");
    }
    else
    {
      setShowPic(false);

      setButtonName("OFF");
    }

  }

  function changeName()
  {
    if(name == "dog")
    {
      setName("tiffany")
    }
    else{
      setName("dog")
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to my website, may name is {name}</h1>
      <button onClick={changeName}> Click Me! </button>

      <button onClick={showCat}>show cat: {buttonName}</button>
      
      { 
        (showPic) ? <img src={"/cats/cat.jpg"}/> : <div></div>
      }

      
    </div>
  )
}

export default Home
